---

- name: Gather Nexus Facts
  hosts: switches
  connection: httpapi
  gather_facts: yes

  tasks:
    - nxos_facts:
    - name: Get the NXOS Running Release
      debug: var=ansible_net_image
    - name: Get the NXOS HW Version
      debug: var=ansible_net_model

